language: generic

dist: trusty
sudo: required

matrix:
    include:
    - os: linux
      compiler: gcc
      env: GCC_VERSION=7
        - CC=gcc-7
        - CXX=g++-7
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'deadsnakes']
          packages: ['g++-7', 'python3.5']
          addons:

before_install:
  - export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"
  - |
    set -e
    set -x
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - sudo python3 get-pip.py

install:
  # system libs
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
  # python libs
  - sudo pip3 install --upgrade pip
  - sudo pip3 install -qq numpy scipy tensorflow==1.7.1 h5py keras
  - # download weights
  - python3 scripts/vgg16_model.py 
  - python3 scripts/sequential_model.py 
  # run CMake
  - mkdir -p build && cd build
  - cmake ..

script:
  - pwd
  - which $CXX
  - $CXX --version
  - make
  - ./main
  - ./seq_model
